# Generated by Django 5.0.6 on 2024-07-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(default='a7ebe170-7f61-428f-9dc3-7e50929eed3a', max_length=255, unique=True),
        ),
    ]
