# Generated by Django 5.0.6 on 2024-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0002_alter_organisation_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(default='aaa8bbb3-6860-4842-9536-c32ea7281816', max_length=255, unique=True),
        ),
    ]
