# Generated by Django 5.0.6 on 2024-07-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_two', '0003_alter_organisation_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='02d92549-566b-4c8e-9962-5d3399b5c1cd', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(default='9b3410ad-cc79-4a9c-9166-e424639a4b6e', max_length=255, unique=True),
        ),
    ]
